name: Run Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent long-running tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgsl-dev  # Required for ViennaRNA
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov  # Testing tools
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --cov=oligobench --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: success()  # Only run if tests pass
